version: '3.8'

services:
  # Main Application
  app:
    container_name: CHATBOT
    build: ./
    restart: unless-stopped
    environment:
      - APP_NAME=CHATBOT
      - HOST=0.0.0.0
      - PORT=8080
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - MODEL=${MODEL}
      - MODEL_E=${MODEL_E}
      - API_KEY=${API_KEY}
      - BASE_URL=${BASE_URL}
    ports:
      - "8080:8080"
    # volumes:
    #   - ./logs:/opt/app/logs
    #   - ./resource:/opt/app/resource:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
